apiVersion: vick.wso2.com/v1alpha1
kind: Cell
metadata:
  name: {{ .Values.name }}
spec:
  gatewayTemplate:
    spec:
      apis:
      - context: info
        definitions:
        - path: /
          method: GET
        backend: hr
        global: true
  servicesTemplates:
  - metadata:
      name: hr
    spec:
      replicas: 1
      container:
        image: docker.io/wso2vick/sampleapp-hr
        ports:
        - containerPort: 8080
        env:
        - name: employeegw_url
          value: {{ .Values.employeeCellName }}--gateway-service
        - name: stockgw_url
          value: {{ .Values.stockCellName }}--gateway-service
      servicePort: 80
  - metadata:
      name: debug
    spec:
      replicas: 1
      container:
        image: docker.io/mirage20/k8s-debug-tools
      servicePort: 80
